styhead migration fixes
Based on the guidance from [1], resolve build errors on styhead.

This resolves 3 issues errors as found with the integration at [2]:

````
DEBUG: Executing shell function do_configure
cat: /home/dan/trellis/oe4t/tegra-demo-distro/build-master/tmp/work/armv8a-oe4t-linux/swupdate/2024.05/defconfig: No such file or directory
WARNING: exit code 1 from a shell command.
```
This error occurs due to the swupdate.inc recipe usage of WORKDIR
instead of UNPACKDIR. Resolved by replacing most references of WORKDIR
to UNPACKDIR as suggested in [1] for swupdate.inc

```
WARNING: swupdate-image-tegra-1.0-r0 do_unpack: swupdate-image-tegra: the directory ${WORKDIR}/${PN} (/home/dan/trellis/oe4t/tegra-demo-distro/build-master/tmp/work/jetson_orin_nano_devkit_nvme-oe4t-linux/swupdate-image-tegra/1.0/swupdate-image-tegra) pointed to by the S variable doesn't exist - please set S within the recipe to point to where the source has been unpacked to
```
This warning is printed due to the setting of S based on WORKDIR
in swupdate.bbclass and the fact that the S directory is no longer
automatically created as discussed in [1].  To resolve, use the guidance
in [1] to set S and UNPACKDIR for recipes which only use file:// sources.

```
ERROR: swupdate-image-tegra-1.0-r0 do_swuimage: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_swuimage(d)
     0003:
File: '/home/dan/trellis/oe4t/tegra-demo-distro/build-master/../layers/meta-swupdate/classes-recipe/swupdate-common.bbclass', lineno: 325, function: do_swuimage
     0321:    list_for_cpio = ["sw-description"]
     0322:    workdir = d.getVar('WORKDIR')
     0323:    s = d.getVar('S')
     0324:    imgdeploydir = d.getVar('SWUDEPLOYDIR')
 *** 0325:    shutil.copyfile(os.path.join(workdir, "sw-description"), os.path.join(s, "sw-description"))
     0326:
...
File: '/usr/lib/python3.10/shutil.py', lineno: 254, function: copyfile
     0250:
     0253:    else:
 *** 0254:        with open(src, 'rb') as fsrc:
```

This error occurs due to the use of WORKDIR as the location of files instead
of UNPACKDIR.  When using the guidance in [1] to set UNPACKDIR there is no
longer a need to copy from WORKDIR to UNPACKDIR since S is UNPACKDIR, so both
the workdir reference and shutil copy can be removed.

1: https://docs.yoctoproject.org/next/migration-guides/migration-5.1.html
2: https://github.com/OE4T/tegra-demo-distro/blob/master/layers/meta-tegrademo/dynamic-layers/meta-swupdate/README.md

Signed-off-by: Dan Walkes <danwalkes@trellis-logic.com>